import React,{useEffect}from 'react';
import qrlogo from '../../assets/Images/qrlogo.png';
import qr1 from '../../assets/Images/ss/white/qr-code.png';
import qr2 from '../../assets/Images/ss/white/qr-code1.png';
import { Button } from '../Button/Button';
import AOS from 'aos';
import 'aos/dist/aos.css';
import './Cards.css';
function Generate_QRCode() {
  useEffect(()=>{
    AOS.init({duration:1500})
  },[]);
  return (
    <>
        <div className="card-container">
              <img id='s3'src={qr2} data-aos='zoom-in-up' alt="ai-ss" data-aos-duration='1500'/>
              <img id='s4'src={qr1} alt="qr-ss" data-aos='zoom-in-up' data-aos-duration='1000'/> 
              <div className="qr-card__wrapper" data-aos='zoom-in-up' data-aos-duration='1200'>
                  <img id='qrilogo'src={qrlogo} alt="pnr-logo"/>
                  <h1 style={{fontFamily:"UrbanistBlack"}}>QR Code Generation</h1>
                  <h1 style={{fontFamily:"UrbanistBlack"}}>Made Easy</h1>
                  <p>Once booked, you'll get a 'Ticket ID',upon entering</p>
                  <p>the ticket ID a QR Code Will be generated by itself </p>
                  <p>which will contain all your train details including</p>
                  <p>train estimated arrival and number of passengers.</p>
                  {/*<div className="card-btn">
                    <Button className='btns' buttonStyle='btn--primary'
                    buttonSize='btn--medium'>Genrate QR Code</Button>
  </div>*/}
                </div>
            </div>
    </>
  );
}

export default Generate_QRCode